# Generated by Django 4.0.3 on 2022-04-01 17:58

import django.core.validators
from django.db import migrations, models
import workshop.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_profile_pet_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), workshop.common.validators.only_letters_validator]),
        ),
    ]
